import type { WorkflowDefinition } from "../../contracts/workflow.js";

export const ARSU_RESEARCH_SLICE_WORKFLOW = {
  schema_version: "0.1",
  workflow_id: "arsu-research-slice",
  workflow_kind: "arsu-research-slice",
  entry_stage_id: "research",
  terminal_stage_ids: [],
  stages: [{ stage_id: "research", title: "Research slice" }],
  work_items: [
    {
      id: "rq-brief",
      stage_id: "research",
      title: "RQ Brief",
      description: "Define the research question, scope, and methodological framing.",
      producer_skill: "deep-research",
      requires: {
        work_items: [],
        contracts: ["specs/project.md", "specs/workflow.yaml", "runs/current/state.yaml"],
        artifact_types: [],
        gate_types: [],
        decision_types: [],
      },
      output: {
        artifact_type: "rq_brief",
        workspace_path: "runs/current/artifacts/rq-brief.md",
        template_ref: "ars:shared/handoff_schemas.md#schema-1-rq-brief",
      },
      instruction: "Produce an RQ Brief grounded in the project contract. Propose, rather than directly apply, any stable project-contract changes.",
      rules: ["Keep the full semantic payload in the artifact.", "Do not edit stable specs or runtime files directly."],
      allowed_writes: ["output_artifact", "contract_patch"],
      validation_profile: "research-artifact",
      completion: {
        artifact_statuses: ["candidate", "accepted"],
        verification_states: ["verified"],
        required_gate_ids: [],
        require_registry: true,
        require_sha256: true,
      },
    },
    {
      id: "bibliography",
      stage_id: "research",
      title: "Bibliography",
      description: "Build a traceable annotated bibliography and documented search strategy.",
      producer_skill: "deep-research",
      requires: {
        work_items: ["rq-brief"],
        contracts: ["specs/project.md", "specs/sources.yaml", "specs/workflow.yaml", "runs/current/state.yaml"],
        artifact_types: ["rq_brief"],
        gate_types: [],
        decision_types: [],
      },
      output: {
        artifact_type: "bibliography",
        workspace_path: "runs/current/artifacts/bibliography.md",
        template_ref: "ars:shared/handoff_schemas.md#schema-2-bibliography",
      },
      instruction: "Produce an annotated bibliography whose sources and search strategy are reproducible and consistent with the RQ Brief.",
      rules: ["Preserve source identifiers for downstream synthesis.", "Propose source-contract changes instead of editing sources.yaml directly."],
      allowed_writes: ["output_artifact", "contract_patch"],
      validation_profile: "research-artifact",
      completion: {
        artifact_statuses: ["candidate", "accepted"],
        verification_states: ["verified"],
        required_gate_ids: [],
        require_registry: true,
        require_sha256: true,
      },
    },
    {
      id: "synthesis",
      stage_id: "research",
      title: "Synthesis Report",
      description: "Integrate the bibliography into themes, debates, gaps, and bounded findings.",
      producer_skill: "deep-research",
      requires: {
        work_items: ["bibliography"],
        contracts: ["specs/project.md", "specs/sources.yaml", "specs/claims.yaml", "runs/current/state.yaml"],
        artifact_types: ["bibliography"],
        gate_types: [],
        decision_types: [],
      },
      output: {
        artifact_type: "synthesis_report",
        workspace_path: "runs/current/artifacts/synthesis-report.md",
        template_ref: "ars:shared/handoff_schemas.md#schema-3-synthesis-report",
      },
      instruction: "Produce a source-traceable synthesis that distinguishes findings, contradictions, limitations, and research gaps.",
      rules: ["Do not strengthen claims beyond the bibliography evidence.", "Propose claim-contract changes instead of editing claims.yaml directly."],
      allowed_writes: ["output_artifact", "contract_patch"],
      validation_profile: "research-artifact",
      completion: {
        artifact_statuses: ["candidate", "accepted"],
        verification_states: ["verified"],
        required_gate_ids: [],
        require_registry: true,
        require_sha256: true,
      },
    },
  ],
} satisfies WorkflowDefinition;

export const ARSU_RESEARCH_SLICE_STATE = {
  schema_version: "0.1",
  run_id: "current",
  workflow_id: "arsu-research-slice",
  status: "not_started",
  active_stage_id: "research",
  pending_decisions: [],
  diagnostics: [],
} as const;
