import { stringify } from "yaml";

import type { CapabilityGraphProfile } from "../contracts/capability-graph.js";

export const RESEARCH_MAIN_GRAPH_PROFILE = {
  schema_version: "2",
  profile_id: "research-main",
  profile_version: "0.1.0",
  capability_registry_version: "0.1.0",
  entries: [{ entry_id: "main", kind: "end-to-end", node_id: "research-question" }],
  nodes: [
    {
      node_id: "research-question",
      kind: "capability",
      capability_id: "design-research-question-formulation",
      input_bindings: [{ role: "project_intent", source: "stable_spec" }],
      expected_outputs: [{ role: "rq_brief", required: true }],
      prerequisites: [],
      required_gate_ids: ["rq-gate"],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "rq-gate",
      kind: "gate",
      input_bindings: [],
      expected_outputs: [],
      prerequisites: ["research-question"],
      required_gate_ids: [],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "methodology",
      kind: "capability",
      capability_id: "design-methodology-design",
      input_bindings: [{ role: "rq_brief", source: "node_output", from_node_id: "research-question" }],
      expected_outputs: [{ role: "methodology_blueprint", required: true }],
      prerequisites: ["rq-gate"],
      required_gate_ids: ["rq-gate"],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "literature",
      kind: "capability",
      capability_id: "discovery-literature-search-screening",
      input_bindings: [
        { role: "rq_brief", source: "node_output", from_node_id: "research-question" },
        { role: "methodology_blueprint", source: "node_output", from_node_id: "methodology" },
      ],
      expected_outputs: [{ role: "annotated_bibliography", required: true }],
      prerequisites: ["methodology"],
      required_gate_ids: ["rq-gate"],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "grading",
      kind: "capability",
      capability_id: "discovery-source-quality-grading",
      input_bindings: [{ role: "annotated_bibliography", source: "node_output", from_node_id: "literature" }],
      expected_outputs: [{ role: "graded_sources", required: true }],
      prerequisites: ["literature"],
      required_gate_ids: [],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "synthesis",
      kind: "capability",
      capability_id: "analysis-evidence-synthesis",
      input_bindings: [{ role: "graded_sources", source: "node_output", from_node_id: "grading" }],
      expected_outputs: [{ role: "synthesis_report", required: true }],
      prerequisites: ["grading"],
      required_gate_ids: [],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
    {
      node_id: "report",
      kind: "capability",
      capability_id: "generation-report-compilation",
      input_bindings: [{ role: "synthesis_report", source: "node_output", from_node_id: "synthesis" }],
      expected_outputs: [{ role: "research_report", required: true }],
      prerequisites: ["synthesis"],
      required_gate_ids: [],
      required_decision_ids: [],
      multiplicity: "one",
      round_role: null,
    },
  ],
  parallel_groups: [],
  subgraphs: [],
  gates: [{ gate_id: "rq-gate", owner_node_id: "rq-gate", policy: "required", verdicts: ["pass", "pass_with_conditions", "fail"] }],
  decisions: [],
  revision_round_template: null,
  override_policy: { failed_gate_requires_decision: true },
} as const satisfies CapabilityGraphProfile;

export const RESEARCH_MAIN_GRAPH_PROFILE_TEXT = `${stringify(RESEARCH_MAIN_GRAPH_PROFILE)}\n`;
