import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const GENERATED_PROFILE_SOURCE = `// Generated by src/arsu-converter/workflow/generate.ts. Do not edit.\nexport { ARSU_V0_1_WORKFLOW } from "../../../arsu-converter/workflow/catalog.js";\n`;

export function generatedProfilePath(repoRoot: string): string {
  return path.join(repoRoot, "src/core/workflow/profiles/arsu-v0-1.generated.ts");
}

export async function generateRuntimeWorkflowProfile(repoRoot: string): Promise<void> {
  const target = generatedProfilePath(repoRoot);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, GENERATED_PROFILE_SOURCE, "utf8");
}

export async function runtimeWorkflowProjectionIsCurrent(repoRoot: string): Promise<boolean> {
  try { return await readFile(generatedProfilePath(repoRoot), "utf8") === GENERATED_PROFILE_SOURCE; }
  catch { return false; }
}

const invoked = process.argv[1] ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false;
if (invoked) await generateRuntimeWorkflowProfile(path.resolve(process.cwd()));
