import {
  CLI_COMMAND_CATALOG,
  CLI_GLOBAL_OPTIONS,
  type CliCommandDefinition,
  type CliCommandGroup,
} from "./command-catalog.js";
import { ACTION_SELECTOR_FAMILY_DISPLAYS } from "../core/contracts/action-selector.js";

const GROUPS: readonly { id: CliCommandGroup; title: string }[] = [
  { id: "bootstrap", title: "Bootstrap" },
  { id: "control-plane", title: "Control plane" },
  { id: "inspection", title: "Inspection" },
  { id: "recovery", title: "Recovery" },
  { id: "context", title: "Context" },
  { id: "governance", title: "Governance" },
  { id: "plugins", title: "Domain Skills" },
];

export function renderCliHandbook(): string {
  const lines = [
    "# ResearchSpec CLI Handbook",
    "",
    "> Generated from the typed public CLI catalog. Do not edit this file by hand.",
    "",
    "This handbook describes the static command surface. It does not expose a live",
    "workflow frontier or authorize a workspace write.",
    "",
    "## Discovery boundary",
    "",
    "1. Run `researchspec --help` to discover the public commands.",
    "2. Run `researchspec <command> --help` (or the relevant `plugin` subcommand help) to inspect syntax and options.",
    "3. For a current workspace action, run `researchspec status --json`, select a returned action selector, and read `researchspec instructions <selector> --json`.",
    "4. Follow the action descriptor's semantic input, availability basis, execution policy and returned `next_selectors`; static help never supplies those facts.",
    "",
    "## Global options",
    "",
    "| Option | Purpose |",
    "| --- | --- |",
    ...CLI_GLOBAL_OPTIONS.map((option) => `| \`${option.flags}\` | ${option.description} |`),
    "",
    "## Action selector families",
    "",
    "A valid selector shape does not imply that the action is available in the current workspace.",
    "",
    "| Family | Accepted forms |",
    "| --- | --- |",
    ...ACTION_SELECTOR_FAMILY_DISPLAYS.map((family) =>
      `| \`${family.id}\` | ${family.patterns.map((pattern) => `\`${pattern}\``).join("<br>")} |`
    ),
    "",
  ];

  for (const group of GROUPS) {
    const commands = CLI_COMMAND_CATALOG.filter((command) => command.group === group.id);
    if (commands.length === 0) continue;
    lines.push(`## ${group.title}`, "");
    for (const command of commands) lines.push(...renderCommandCard(command));
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderCommandCard(command: CliCommandDefinition): string[] {
  const invocation = command.path.length === 1
    ? `researchspec ${command.syntax}`
    : `researchspec ${command.path[0]} ${command.syntax}`;
  const related = command.related
    .map((id) => CLI_COMMAND_CATALOG.find((candidate) => candidate.id === id))
    .filter((candidate): candidate is CliCommandDefinition => Boolean(candidate))
    .map((candidate) => `\`${candidate.path.join(" ")}\``)
    .join(", ");
  const lines = [
    `### \`${invocation}\``,
    "",
    command.description,
    "",
    `- Workspace: \`${command.workspace}\``,
    `- Static effect: \`${command.effect}\``,
    `- Related commands: ${related || "none"}`,
  ];

  if (command.options.length > 0) {
    lines.push(
      "",
      "| Command option | Required | Purpose |",
      "| --- | --- | --- |",
      ...command.options.map((option) =>
        `| \`${option.flags}\` | ${option.required ? "yes" : "no"} | ${option.description} |`
      ),
    );
  }
  lines.push("");
  return lines;
}
