import {
  CLI_COMMAND_CATALOG,
  CLI_GLOBAL_OPTIONS,
  type CliCommandDefinition,
  type CliCommandGroup,
} from "./command-catalog.js";
import {
  CONTROL_SELECTOR_FAMILY_DISPLAYS,
  INSPECTION_SELECTOR_FAMILY_DISPLAYS,
} from "../core/contracts/control-selector.js";

const GROUPS: readonly { id: CliCommandGroup; title: string }[] = [
  { id: "bootstrap", title: "Bootstrap" },
  { id: "control-plane", title: "Control plane" },
  { id: "inspection", title: "Inspection" },
  { id: "recovery", title: "Recovery" },
  { id: "context", title: "Context" },
  { id: "governance", title: "Governance" },
  { id: "plugins", title: "Domain Skills" },
];

export interface MdxCommandPage {
  filename: string;
  content: string;
  sidebarPosition: number;
}

export function renderCliHandbook(): string {
  const lines = [
    "# ResearchSpec CLI Handbook",
    "",
    "> Generated from the typed public CLI catalog. Do not edit this file by hand.",
    "",
    "This handbook describes the static command surface. It does not expose a live",
    "workflow frontier or authorize a workspace write.",
    "",
    "## Discovery boundary",
    "",
    "1. Run `researchspec --help` to discover the public commands.",
    "2. Run `researchspec <command> --help` (or the relevant `plugin` subcommand help) to inspect syntax and options.",
    "3. For a current workspace action, run `researchspec status --json`, select a returned action selector, and read `researchspec instructions <selector> --json`.",
    "4. Follow the selector-specific prerequisites, handoff roles, confirmation points and allowed actions; static help never supplies those facts.",
    "",
    "## Global options",
    "",
    "| Option | Purpose |",
    "| --- | --- |",
    ...CLI_GLOBAL_OPTIONS.map((option) => `| \`${option.flags}\` | ${option.description} |`),
    "",
    "## Current selector families",
    "",
    "A valid selector shape does not imply that the action is available in the current workspace.",
    "",
    "| Family | Accepted forms |",
    "| --- | --- |",
    ...selectorDisplays().map((family) =>
      `| \`${family.id}\` | ${family.patterns.map((pattern) => `\`${pattern}\``).join("<br>")} |`
    ),
    "",
  ];

  for (const group of GROUPS) {
    const commands = CLI_COMMAND_CATALOG.filter((command) => command.group === group.id);
    if (commands.length === 0) continue;
    lines.push(`## ${group.title}`, "");
    for (const command of commands) lines.push(...renderCommandCard(command));
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderMdxCommandPages(): MdxCommandPage[] {
  const pages: MdxCommandPage[] = [];
  let position = 0;

  for (const group of GROUPS) {
    const commands = CLI_COMMAND_CATALOG.filter((command) => command.group === group.id);
    if (commands.length === 0) continue;
    for (const command of commands) {
      position += 1;
      const filename = command.path.join("-") + ".mdx";
      const content = renderMdxCommandPage(command, position, group.title);
      pages.push({ filename, content, sidebarPosition: position });
    }
  }

  return pages;
}

export function renderMdxCliSidebar(): string {
  const lines = [
    "// Generated from the typed public CLI catalog. Do not edit by hand.",
    "export const cliSidebar = [",
  ];

  for (const group of GROUPS) {
    const commands = CLI_COMMAND_CATALOG.filter((command) => command.group === group.id);
    if (commands.length === 0) continue;
    lines.push(`  { type: "category" as const, label: "${group.title}", items: [`);
    for (const command of commands) {
      lines.push(`    "cli/${command.path.join("-")}",`);
    }
    lines.push("  ] },");
  }

  lines.push("];");
  return `${lines.join("\n")}\n`;
}

function renderMdxCommandPage(command: CliCommandDefinition, position: number, group: string): string {
  const invocation = command.path.length === 1
    ? `researchspec ${command.syntax}`
    : `researchspec ${command.path[0]} ${command.syntax}`;

  const related = command.related
    .map((id) => CLI_COMMAND_CATALOG.find((candidate) => candidate.id === id))
    .filter((candidate): candidate is CliCommandDefinition => Boolean(candidate))
    .map((candidate) => `[\`${candidate.path.join(" ")}\`](./${candidate.path.join("-")})`)
    .join(", ");

  const optionRows = command.options.length > 0
    ? [
        "",
        "| Option | Required | Description |",
        "| --- | --- | --- |",
        ...command.options.map((opt) =>
          `| \`${opt.flags}\` | ${opt.required ? "yes" : "no"} | ${opt.description} |`
        ),
      ]
    : [];

  return [
    "---",
    `sidebar_position: ${String(position)}`,
    `title: "${command.path.join(" ")}"`,
    `description: "${command.description}"`,
    "---",
    `import Tabs from "@theme/Tabs";`,
    `import TabItem from "@theme/TabItem";`,
    "",
    `# \`${invocation}\``,
    "",
    command.description,
    "",
    `- **Group**: ${group}`,
    `- **Workspace**: \`${command.workspace}\``,
    `- **Effect**: \`${command.effect}\``,
    `- **Related**: ${related || "none"}`,
    ...optionRows,
    ...renderPayloadSection(command, "mdx"),
    "",
  ].join("\n").trimEnd() + "\n";
}

function selectorDisplays(): ReadonlyArray<{ id: string; patterns: readonly string[] }> {
  const seen = new Set<string>();
  return [...CONTROL_SELECTOR_FAMILY_DISPLAYS, ...INSPECTION_SELECTOR_FAMILY_DISPLAYS]
    .filter((item) => !seen.has(item.id) && seen.add(item.id));
}

function renderCommandCard(command: CliCommandDefinition): string[] {
  const invocation = command.path.length === 1
    ? `researchspec ${command.syntax}`
    : `researchspec ${command.path[0]} ${command.syntax}`;
  const related = command.related
    .map((id) => CLI_COMMAND_CATALOG.find((candidate) => candidate.id === id))
    .filter((candidate): candidate is CliCommandDefinition => Boolean(candidate))
    .map((candidate) => `\`${candidate.path.join(" ")}\``)
    .join(", ");
  const lines = [
    `### \`${invocation}\``,
    "",
    command.description,
    "",
    `- Workspace: \`${command.workspace}\``,
    `- Static effect: \`${command.effect}\``,
    `- Related commands: ${related || "none"}`,
  ];

  if (command.options.length > 0) {
    lines.push(
      "",
      "| Command option | Required | Purpose |",
      "| --- | --- | --- |",
      ...command.options.map((option) =>
        `| \`${option.flags}\` | ${option.required ? "yes" : "no"} | ${option.description} |`
      ),
    );
  }
  lines.push(...renderPayloadSection(command, "markdown"));
  lines.push("");
  return lines;
}

function renderPayloadSection(command: CliCommandDefinition, mode: "markdown" | "mdx"): string[] {
  const payload = command.payload;
  const lines = ["", "#### Input shape", "", payload.summary];
  if (payload.schema) lines.push("", `Runtime schema: \`${payload.schema}\`.`);
  if (payload.fields.length > 0) {
    lines.push(
      "",
      "| Field or option | Type | Required | Meaning |",
      "| --- | --- | --- | --- |",
      ...payload.fields.map((field) =>
        `| \`${tableCell(field.name)}\` | \`${tableCell(field.type)}\` | ${field.required ? "yes" : "no"} | ${tableCell(field.description)} |`
      ),
    );
  }
  if (payload.constraints.length > 0) {
    lines.push("", "Constraints:", "", ...payload.constraints.map((constraint) => `- ${constraint}`));
  }
  if (mode === "mdx") lines.push("");
  return lines;
}

function tableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
