/**
 * Bilingual concept vocabulary for Procedure discovery.
 *
 * A concept is a research meaning, not a catalog entry. Groups never name a
 * Procedure ID: the same surface forms are expanded on the query side and on
 * the document side so both sides of the comparison stay symmetric.
 */
export const CONCEPT_GROUPS: readonly (readonly string[])[] = [
  ["research", "study", "studies", "研究", "科研"],
  ["deep research", "深度研究", "深入研究"],
  ["literature review", "literature", "文献综述", "文献回顾", "综述", "文献", "书目"],
  ["literature search", "文献检索", "文献搜索", "文献筛查"],
  ["search", "检索", "搜索", "查找"],
  ["screening", "screen", "prisma", "systematic review", "筛选", "初筛", "纳入"],
  ["duplicate", "deduplicate", "duplicates", "重复", "去重", "查重"],
  ["synthesis", "synthesize", "综合", "整合", "归纳"],
  ["evidence", "证据", "凭证"],
  ["claim", "论断", "主张", "断言"],
  ["fact check", "事实核查"],
  ["citation", "引用", "引文", "引注"],
  ["reference", "bibliography", "参考文献", "参考书目", "出处"],
  ["check", "verify", "verification", "audit", "检查", "核验", "校验", "验证", "核查"],
  ["outline", "大纲", "提纲"],
  ["manuscript", "paper", "bibliography", "稿件", "手稿", "论文"],
  ["draft", "drafting", "write", "writing", "起草", "撰写", "写作"],
  ["revision", "revise", "patch", "修订", "修改"],
  ["reviewer", "审稿人", "评审人"],
  ["reply", "response", "respond", "回复", "答复", "回应"],
  ["response to reviewers", "review response", "response letter", "审稿回复", "审稿意见回复", "回复审稿人", "回复信"],
  ["reviewer comment", "reviewer feedback", "comment", "comments", "审稿意见", "评审意见", "审稿评论", "意见"],
  ["itemize", "atomize", "atomization", "逐条", "分条", "逐点"],
  ["rebuttal", "rebuttal letter", "答辩回复", "答复审稿"],
  ["peer review", "同行评审", "审稿", "评审"],
  ["review", "审阅", "评估意见"],
  ["abstract", "摘要"],
  ["keywords", "关键词"],
  ["argument", "论证", "论点"],
  ["methodology", "method", "methods", "研究方法", "方法学", "研究设计"],
  ["meta analysis", "元分析", "荟萃分析"],
  ["risk of bias", "偏倚风险", "偏倚"],
  ["patent", "专利"],
  ["prior art", "现有技术", "在先技术"],
  ["patent claim", "权利要求"],
  ["patent application", "专利申请", "专利交底书", "发明交底"],
  ["office action", "审查意见", "审查意见答复", "审查通知书"],
  ["patent reading", "专利阅读", "专利文献阅读", "专利分析"],
  ["invention mining", "专利挖掘", "创新挖掘"],
  ["patent docket", "专利台账", "台账"],
  ["history", "historical", "历史", "史料"],
  ["archive", "archives", "档案", "档案馆"],
  ["heritage", "文化遗产", "文保"],
  ["museum", "博物馆", "馆藏"],
  ["finance", "financial", "金融", "财务"],
  ["investment", "投资", "投资组合"],
  ["accounting", "会计"],
  ["audit", "审计"],
  ["valuation", "估值", "估值分析"],
  ["statement", "财务报表", "报表", "三张表"],
  ["fundamentals", "基本面", "基本面分析"],
  ["competitive position", "竞争地位", "竞争格局"],
  ["corporate risk", "企业风险", "公司风险"],
  ["stock", "股票", "equity", "股权"],
  ["education", "educational", "教育", "教学"],
  ["curriculum", "课程", "课程设计", "教案"],
  ["assessment", "评估", "测评"],
  ["classroom", "课堂", "课堂教学"],
  ["materials science", "materials", "材料科学", "材料"],
  ["simulation", "模拟", "仿真"],
  ["compliance", "合规", "合规性"],
  ["source quality", "quality", "来源质量", "证据质量", "质量", "低质量", "分级"],
  ["hypothesis", "假设", "研究假设"],
  ["experiment", "实验", "实验设计"],
  ["data", "数据"],
  ["figure", "chart", "figures", "图表", "插图", "配图"],
  ["format", "格式", "格式转换"],
  ["ethics", "伦理", "研究伦理"],
  ["reproducibility", "reproducible", "可复现", "可重复"],
  ["research gap", "研究空白", "研究缺口"],
  ["risk", "风险"],
  ["monitoring", "监测", "监控"],
  ["report", "报告", "研究报告"],
  ["socratic", "苏格拉底", "启发式提问"],
  ["humanization", "人性化", "去ai味"],
  ["contamination", "污染"],
  ["temporal integrity", "时效性", "时间一致性"],
  ["preflight", "预检", "预检查"],
  ["submission", "投稿", "提交"],
];

/** Bounded stopword list; content terms outside the lexicon remain matchable. */
export const STOPWORDS: ReadonlySet<string> = new Set([
  "a", "an", "the", "of", "for", "to", "and", "or", "in", "on", "with", "is", "are", "be",
  "do", "does", "did", "can", "could", "would", "should", "will", "shall", "may", "want",
  "need", "help", "please", "how", "what", "which", "when", "where", "this", "that", "these",
  "those", "it", "its", "i", "me", "my", "we", "our", "you", "your", "let", "get", "make",
  "give", "use", "using", "about", "into", "from", "then", "than", "some", "any", "all",
  "的", "了", "和", "与", "或", "在", "是", "有", "为", "我", "我们", "你", "你们", "请",
  "帮", "帮忙", "需要", "想", "要", "如何", "怎么", "什么", "可以", "一个", "这个", "那个",
  "一些", "进行", "做", "把", "给", "对", "用", "以及", "然后", "并且", "如果", "因为",
]);

/** Upper bound on sibling terms a single concept contributes to one text. */
export const CONCEPT_EXPANSION_LIMIT = 8;

/** Upper bound on concept terms added to one analyzed text in total. */
export const CONCEPT_TOTAL_LIMIT = 40;
