import type { CapabilityAuthoringSource } from "./author.js";

const CC_BY_NC = "CC BY-NC 4.0";

export const M1_AUTHORING_SOURCES: readonly CapabilityAuthoringSource[] = [
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/research-question-formulation.md",
    capability_id: "design-research-question-formulation",
    title: "Research Question Formulation",
    description: "Turns a project intent into a FINER-scored research question brief with scope boundaries and bound sub-questions.",
    class: "design",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M1-04",
    knowledge_sources: [
      { knowledge_id: "finer-framework", extraction_artifact_id: "KP-M1-02", output_path: "knowledge/finer-framework.md" },
      { knowledge_id: "finer-socratic-questions", extraction_artifact_id: "KP-M1-02b", output_path: "knowledge/finer-socratic-questions.md" },
    ],
    inputs: [{ role: "project_intent", schema_ref: "specs.project", required: true, source_policy: "stable_spec" }],
    outputs: [{ role: "rq_brief", schema_ref: "rq-brief.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/methodology-design.md",
    capability_id: "design-methodology-design",
    title: "Methodology Design",
    description: "Selects a paradigm, methods, data strategy and analysis framework coherent with the confirmed research question, with bounded human-subjects administration and preregistration handoff.",
    class: "design",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M1-05",
    knowledge_sources: [
      { knowledge_id: "irb-decision-tree", extraction_artifact_id: "KP-M5-20", output_path: "knowledge/irb-decision-tree.md" },
      { knowledge_id: "irb-terminology-glossary", extraction_artifact_id: "KP-M5-23", output_path: "knowledge/irb-terminology-glossary.md" },
      { knowledge_id: "equator-guidelines", extraction_artifact_id: "KP-M5-21", output_path: "knowledge/equator-guidelines.md" },
      { knowledge_id: "preregistration-guide", extraction_artifact_id: "KP-M5-22", output_path: "knowledge/preregistration-guide.md" },
    ],
    inputs: [{ role: "rq_brief", schema_ref: "rq-brief.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "methodology_blueprint", schema_ref: "methodology-blueprint.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/literature-search-screening.md",
    capability_id: "discovery-literature-search-screening",
    title: "Literature Search And Screening",
    description: "Runs a systematic, reproducible search and screening process and produces an annotated bibliography with claim-specific coverage and PRISMA-style documentation.",
    class: "discovery",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M1-01",
    knowledge_sources: [
      { knowledge_id: "prisma-documentation", extraction_artifact_id: "KP-M1-03", output_path: "knowledge/prisma-documentation.md" },
      { knowledge_id: "corpus-iron-rules", extraction_artifact_id: "KP-M1-04", output_path: "knowledge/corpus-iron-rules.md" },
    ],
    inputs: [
      { role: "rq_brief", schema_ref: "rq-brief.v1", required: true, source_policy: "node_output" },
      { role: "methodology_blueprint", schema_ref: "methodology-blueprint.v1", required: true, source_policy: "node_output" },
    ],
    outputs: [{ role: "annotated_bibliography", schema_ref: "annotated-bibliography.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/source-quality-grading.md",
    capability_id: "discovery-source-quality-grading",
    title: "Source Quality Grading",
    description: "Grades each source by evidence level, predatory-journal red flags and conflicts of interest.",
    class: "verification",
    node_kind: "checker",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M1-02",
    knowledge_sources: [
      { knowledge_id: "evidence-hierarchy", extraction_artifact_id: "KP-M1-01", output_path: "knowledge/evidence-hierarchy.md" },
    ],
    inputs: [{ role: "annotated_bibliography", schema_ref: "annotated-bibliography.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "graded_sources", schema_ref: "graded-sources.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/evidence-synthesis.md",
    capability_id: "analysis-evidence-synthesis",
    title: "Evidence Synthesis",
    description: "Synthesizes graded sources into a convergent/divergent evidence map with claim-intent and citation emissions.",
    class: "analysis",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M1-03",
    knowledge_sources: [
      { knowledge_id: "claim-intent-emission", extraction_artifact_id: "KP-M1-05", output_path: "knowledge/claim-intent-emission.md" },
      { knowledge_id: "claim-intent-canonical", extraction_artifact_id: "KP-M1-05b", output_path: "knowledge/claim-intent-canonical.md" },
      { knowledge_id: "three-layer-citation", extraction_artifact_id: "KP-M1-06", output_path: "knowledge/three-layer-citation.md" },
    ],
    inputs: [{ role: "graded_sources", schema_ref: "graded-sources.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "synthesis_report", schema_ref: "synthesis-report.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m1/report-compilation.md",
    capability_id: "generation-report-compilation",
    title: "Research Report Compilation",
    description: "Compiles the synthesis and method blueprint into a complete APA-style research report.",
    class: "generation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC_BY_NC,
    extraction_artifact_id: "CAP-M2-04",
    knowledge_sources: [
      { knowledge_id: "academic-writing-style", extraction_artifact_id: "KP-M2-01", output_path: "knowledge/academic-writing-style.md" },
      { knowledge_id: "writing-quality-check", extraction_artifact_id: "KP-M2-07", output_path: "knowledge/writing-quality-check.md" },
    ],
    inputs: [
      { role: "synthesis_report", schema_ref: "synthesis-report.v1", required: true, source_policy: "node_output" },
      { role: "methodology_blueprint", schema_ref: "methodology-blueprint.v1", required: true, source_policy: "node_output" },
    ],
    outputs: [{ role: "research_report", schema_ref: "research-report.v1", required: true }],
  },
];
