import type { CapabilityAuthoringSource } from "./author.js";

const CC = "CC BY-NC 4.0";

export const M2_AUTHORING_SOURCES: readonly CapabilityAuthoringSource[] = [
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/writing-intake.md",
    capability_id: "design-writing-intake",
    title: "Writing Intake",
    description: "Collects paper configuration, preregistration handoff, review-target context, domain profile, and style calibration for writing work.",
    class: "design",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-01",
    knowledge_sources: [{ knowledge_id: "style-calibration", extraction_artifact_id: "KP-M2-06", output_path: "knowledge/style-calibration.md" }, { knowledge_id: "preregistration-guide", extraction_artifact_id: "KP-M5-22", output_path: "knowledge/preregistration-guide.md" }, { knowledge_id: "output-language-pair", extraction_artifact_id: "KP-M2-09", output_path: "knowledge/output-language-pair.md" }],
    inputs: [{ role: "project_intent", schema_ref: "specs.project", required: true, source_policy: "stable_spec" }],
    outputs: [{ role: "writing_configuration", schema_ref: "writing-configuration.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/manuscript-structure-design.md",
    capability_id: "design-manuscript-structure-design",
    title: "Manuscript Structure Design",
    description: "Designs paper structure, outline, word budget, evidence mapping, and formative review-criteria coverage.",
    class: "design",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-02",
    knowledge_sources: [{ knowledge_id: "paper-structure-patterns", extraction_artifact_id: "KP-M2-08", output_path: "knowledge/paper-structure-patterns.md" }, { knowledge_id: "abstract-guide", extraction_artifact_id: "KP-M2-02", output_path: "knowledge/abstract-guide.md" }, { knowledge_id: "output-language-pair", extraction_artifact_id: "KP-M2-09", output_path: "knowledge/output-language-pair.md" }],
    inputs: [{ role: "writing_configuration", schema_ref: "writing-configuration.v1", required: true, source_policy: "node_output" }, { role: "annotated_bibliography", schema_ref: "annotated-bibliography.v1", required: true, source_policy: ["handoff", "node_output"] }],
    outputs: [{ role: "paper_outline", schema_ref: "paper-outline.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/argument-blueprint.md",
    capability_id: "design-argument-blueprint",
    title: "Argument Blueprint",
    description: "Builds claim-evidence-reasoning chains and handles counterarguments.",
    class: "design",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-03",
    knowledge_sources: [{ knowledge_id: "academic-writing-style", extraction_artifact_id: "KP-M2-01", output_path: "knowledge/academic-writing-style.md" }, { knowledge_id: "anti-leakage", extraction_artifact_id: "KP-M2-03", output_path: "knowledge/anti-leakage.md" }, { knowledge_id: "paper-structure-patterns", extraction_artifact_id: "KP-M2-08", output_path: "knowledge/paper-structure-patterns.md" }],
    inputs: [{ role: "paper_outline", schema_ref: "paper-outline.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "argument_blueprint", schema_ref: "argument-blueprint.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/manuscript-drafting.md",
    capability_id: "generation-manuscript-drafting",
    title: "Manuscript Drafting",
    description: "Writes manuscript sections and scope-authorized revision patches from outline and argument blueprint.",
    class: "generation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-04",
    knowledge_sources: [{ knowledge_id: "academic-writing-style", extraction_artifact_id: "KP-M2-01", output_path: "knowledge/academic-writing-style.md" }, { knowledge_id: "anti-leakage", extraction_artifact_id: "KP-M2-03", output_path: "knowledge/anti-leakage.md" }, { knowledge_id: "writing-quality", extraction_artifact_id: "KP-M2-07", output_path: "knowledge/writing-quality.md" }, { knowledge_id: "abstract-guide", extraction_artifact_id: "KP-M2-02", output_path: "knowledge/abstract-guide.md" }, { knowledge_id: "output-language-pair", extraction_artifact_id: "KP-M2-09", output_path: "knowledge/output-language-pair.md" }],
    inputs: [{ role: "argument_blueprint", schema_ref: "argument-blueprint.v1", required: true, source_policy: "node_output" }, { role: "synthesis_report", schema_ref: "synthesis-report.v1", required: true, source_policy: ["handoff", "node_output"] }, { role: "writing_configuration", schema_ref: "writing-configuration.v1", required: false, source_policy: ["handoff", "node_output"] }],
    outputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/abstract-writing.md",
    capability_id: "generation-abstract-writing",
    title: "Abstract Writing",
    description: "Writes independent bilingual abstract and keywords.",
    class: "generation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-05",
    knowledge_sources: [{ knowledge_id: "abstract-guide", extraction_artifact_id: "KP-M2-02", output_path: "knowledge/abstract-guide.md" }, { knowledge_id: "writing-quality", extraction_artifact_id: "KP-M2-07", output_path: "knowledge/writing-quality.md" }, { knowledge_id: "output-language-pair", extraction_artifact_id: "KP-M2-09", output_path: "knowledge/output-language-pair.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: "node_output" }, { role: "writing_configuration", schema_ref: "writing-configuration.v1", required: false, source_policy: ["handoff", "node_output"] }],
    outputs: [{ role: "abstract", schema_ref: "abstract.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m2/citation-format-compliance.md",
    capability_id: "check-citation-format-compliance",
    title: "Citation Format Compliance",
    description: "Validates in-text citations and reference list formatting.",
    class: "verification",
    node_kind: "checker",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M2-06",
    knowledge_sources: [{ knowledge_id: "citation-format-standards", extraction_artifact_id: "KP-M2-05", output_path: "knowledge/citation-format-standards.md" }, { knowledge_id: "apa7-chinese-citation-guide", extraction_artifact_id: "KP-M5-28", output_path: "knowledge/apa7-chinese-citation-guide.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "citation_compliance_report", schema_ref: "citation-compliance.v1", required: true }],
  }
];
