import type { CapabilityAuthoringSource } from "./author.js";
import { checkerSource } from "./checker-source.js";

const CC = "CC BY-NC 4.0";

export const M4_AUTHORING_SOURCES: readonly CapabilityAuthoringSource[] = [
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m4/revision-roadmap-parsing.md",
    capability_id: "transform-revision-roadmap-parsing",
    title: "Revision Roadmap Parsing",
    description: "Converts unstructured reviewer comments into a structured roadmap.",
    class: "transformation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M4-01",
    knowledge_sources: [{ knowledge_id: "revision-patch-protocol", extraction_artifact_id: "KP-M4-01", output_path: "knowledge/revision-patch-protocol.md" }],
    inputs: [
      { role: "review_comments", schema_ref: "review-comments.v1", required: true, source_policy: "node_output" },
      { role: "rebuttal_draft", schema_ref: "rebuttal-draft.v1", required: false, source_policy: "handoff" },
    ],
    outputs: [
      { role: "revision_roadmap", schema_ref: "revision-roadmap.v1", required: true },
      { role: "rebuttal_qa_report", schema_ref: "rebuttal-qa.v1", required: false },
    ],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m4/revision-patching.md",
    capability_id: "transform-revision-patching",
    title: "Revision Patching",
    description: "Deterministically anchors and applies revision patches fail-closed.",
    class: "transformation",
    node_kind: "checker",
    execution_type: "mixed",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M4-02",
    knowledge_sources: [{ knowledge_id: "revision-patch-protocol", extraction_artifact_id: "KP-M4-01", output_path: "knowledge/revision-patch-protocol.md" }],
    inputs: [{ role: "revision_patch", schema_ref: "revision-patch.v1", required: true, source_policy: "node_output" }],
    outputs: [
      { role: "patched_manuscript", schema_ref: "patched-manuscript.v1", required: true },
      { role: "response_to_reviewers", schema_ref: "response-to-reviewers.v1", required: false },
    ],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m4/format-rendering.md",
    capability_id: "generation-format-rendering",
    title: "Format Rendering",
    description: "Converts the final manuscript into declared output formats.",
    class: "generation",
    node_kind: "producer",
    execution_type: "mixed",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M4-03",
    knowledge_sources: [{ knowledge_id: "latex-template", extraction_artifact_id: "KP-M4-04", output_path: "knowledge/latex-template.md" }, { knowledge_id: "submission-guide", extraction_artifact_id: "KP-M4-05", output_path: "knowledge/submission-guide.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: ["handoff", "node_output"] }],
    outputs: [{ role: "formatted_manuscript", schema_ref: "formatted-manuscript.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m4/terminal-policy-gate.md",
    capability_id: "check-terminal-policy-gate",
    title: "Terminal Policy Gate",
    description: "Applies the finalizer policy before submission package creation.",
    class: "verification",
    node_kind: "checker",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M4-04",
    knowledge_sources: [{ knowledge_id: "terminal-firm-rules", extraction_artifact_id: "KP-M4-02", output_path: "knowledge/terminal-firm-rules.md" }],
    inputs: [{ role: "formatted_manuscript", schema_ref: "formatted-manuscript.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "terminal_policy_report", schema_ref: "terminal-policy.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m4/temporal-integrity.md",
    capability_id: "check-temporal-integrity-verification",
    title: "Temporal Integrity Verification",
    description: "Runs five-pass temporal lint against manuscript claims.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M4-05",
    ...checkerSource("temporal", "temporal", "temporal-integrity", "temporal-integrity-script"),
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [
      { role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: ["handoff", "node_output"] },
      { role: "timeline", schema_ref: "timeline.v1", required: false, source_policy: ["handoff", "node_output"] },
      { role: "citation_provenance", schema_ref: "citation-provenance.v1", required: false, source_policy: ["handoff", "node_output"] },
    ],
    outputs: [{ role: "temporal_audit_report", schema_ref: "temporal-audit.v1", required: true }],
  }
];
