import type { CapabilityAuthoringSource } from "./author.js";

const CC = "CC BY-NC 4.0";

export const M5_AUTHORING_SOURCES: readonly CapabilityAuthoringSource[] = [
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/meta-analysis.md",
    capability_id: "cap.analysis.meta-analysis",
    title: "Meta Analysis",
    description: "Quantitative synthesis for systematic review.",
    class: "analysis",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-01",
    knowledge_sources: [{ knowledge_id: "systematic-review-protocol", extraction_artifact_id: "KP-M5-01", output_path: "knowledge/systematic-review-protocol.md" }],
    inputs: [{ role: "systematic_review_corpus", schema_ref: "systematic-review-corpus.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "meta_analysis_report", schema_ref: "meta-analysis.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/risk-of-bias.md",
    capability_id: "cap.analysis.risk-of-bias-assessment",
    title: "Risk of Bias Assessment",
    description: "RoB 2 and ROBINS-I assessments.",
    class: "analysis",
    node_kind: "checker",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-02",
    knowledge_sources: [{ knowledge_id: "systematic-review-toolkit", extraction_artifact_id: "KP-M5-02", output_path: "knowledge/systematic-review-toolkit.md" }],
    inputs: [{ role: "systematic_review_corpus", schema_ref: "systematic-review-corpus.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "rob_assessment", schema_ref: "rob-assessment.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/socratic-mentoring.md",
    capability_id: "cap.transform.socratic-mentoring",
    title: "Socratic Mentoring",
    description: "Guided question-driven research or planning dialogue.",
    class: "transformation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-03",
    knowledge_sources: [{ knowledge_id: "socratic-protocol", extraction_artifact_id: "KP-M5-03", output_path: "knowledge/socratic-protocol.md" }, { knowledge_id: "socratic-framework", extraction_artifact_id: "KP-M5-04", output_path: "knowledge/socratic-framework.md" }],
    inputs: [{ role: "project_intent", schema_ref: "specs.project", required: true, source_policy: "node_output" }],
    outputs: [{ role: "socratic_session_notes", schema_ref: "socratic-session.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/figure-generation.md",
    capability_id: "cap.generation.figure-generation",
    title: "Figure Generation",
    description: "Generates publication-grade figure code.",
    class: "generation",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-04",
    knowledge_sources: [{ knowledge_id: "visualization-standards", extraction_artifact_id: "KP-M5-06", output_path: "knowledge/visualization-standards.md" }, { knowledge_id: "vlm-figure-check", extraction_artifact_id: "KP-M5-07", output_path: "knowledge/vlm-figure-check.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "figure_code", schema_ref: "figure-code.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/literature-monitoring.md",
    capability_id: "cap.discovery.literature-monitoring",
    title: "Literature Monitoring",
    description: "Post-publication monitoring configuration.",
    class: "discovery",
    node_kind: "producer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-05",
    knowledge_sources: [{ knowledge_id: "monitoring-strategies", extraction_artifact_id: "KP-M5-08", output_path: "knowledge/monitoring-strategies.md" }],
    inputs: [{ role: "research_question", schema_ref: "research-question.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "monitoring_config", schema_ref: "monitoring-config.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/claim-faithfulness.md",
    capability_id: "cap.check.claim-faithfulness-audit",
    title: "Claim Faithfulness Audit",
    description: "LLM-as-judge claim-source alignment audit.",
    class: "verification",
    node_kind: "checker",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-06",
    knowledge_sources: [{ knowledge_id: "claim-audit-calibration", extraction_artifact_id: "KP-M5-09", output_path: "knowledge/claim-audit-calibration.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "claim_audit_report", schema_ref: "claim-audit.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/compliance-check.md",
    capability_id: "cap.check.compliance-check",
    title: "Compliance Check",
    description: "PRISMA-trAIce and RAISE advisory compliance.",
    class: "verification",
    node_kind: "observer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-07",
    knowledge_sources: [{ knowledge_id: "raise-framework", extraction_artifact_id: "KP-M5-10", output_path: "knowledge/raise-framework.md" }, { knowledge_id: "prisma-traice", extraction_artifact_id: "KP-M5-11", output_path: "knowledge/prisma-traice.md" }],
    inputs: [{ role: "manuscript_draft", schema_ref: "manuscript-draft.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "compliance_report", schema_ref: "compliance.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/collaboration-depth.md",
    capability_id: "cap.check.collaboration-depth-observer",
    title: "Collaboration Depth Observer",
    description: "Advisory four-dimension collaboration depth score.",
    class: "verification",
    node_kind: "observer",
    execution_type: "llm",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-08",
    knowledge_sources: [{ knowledge_id: "collaboration-depth-rubric", extraction_artifact_id: "KP-M5-12", output_path: "knowledge/collaboration-depth-rubric.md" }],
    inputs: [{ role: "run_context", schema_ref: "run-context.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "collaboration_depth_report", schema_ref: "collaboration-depth.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/submission-package-verifier.md",
    capability_id: "cap.check.submission-package-verifier",
    title: "Submission Package Verifier",
    description: "Deterministic submission package verifier.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-09",
    script_validator: { validator_id: "submission-package-verifier-script", entrypoint_path: "validators/submission-package-verifier.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "terminal-firm-rules", extraction_artifact_id: "KP-M4-02", output_path: "knowledge/terminal-firm-rules.md" }, { knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "submission_package", schema_ref: "submission-package.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "submission_package_report", schema_ref: "submission-package-check.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/passport-verifier.md",
    capability_id: "cap.check.passport-verifier",
    title: "Passport Verifier",
    description: "Deterministic material passport verifier.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-10",
    script_validator: { validator_id: "passport-verifier-script", entrypoint_path: "validators/passport-verifier.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "material_passport", schema_ref: "material-passport.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "passport_report", schema_ref: "passport-check.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/citation-existence.md",
    capability_id: "cap.check.citation-existence-verification",
    title: "Citation Existence Verification",
    description: "Deterministic resolver-based citation existence gate.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-11",
    script_validator: { validator_id: "citation-verification-gate-script", entrypoint_path: "validators/citation-verification-gate.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "annotated_bibliography", schema_ref: "annotated-bibliography.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "citation_verification_report", schema_ref: "citation-existence.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/pdf-read-preflight.md",
    capability_id: "cap.check.pdf-read-preflight",
    title: "PDF Read Preflight",
    description: "Deterministic PDF extraction preflight.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-12",
    script_validator: { validator_id: "pdf-read-preflight-script", entrypoint_path: "validators/pdf-read-preflight.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "pdf_path", schema_ref: "pdf.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "pdf_preflight_report", schema_ref: "pdf-preflight.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/citation-verification-summary.md",
    capability_id: "cap.check.citation-verification-summary",
    title: "Citation Verification Summary",
    description: "Deterministic citation verification summary.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-13",
    script_validator: { validator_id: "citation-verification-summary-script", entrypoint_path: "validators/citation-verification-summary.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "citation_verification_report", schema_ref: "citation-existence.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "citation_summary", schema_ref: "citation-summary.v1", required: true }],
  },
  {
    procedure_path: "src/arsu-converter/authoring/procedures/m5/contamination-signals.md",
    capability_id: "cap.check.contamination-signals",
    title: "Contamination Signals",
    description: "Deterministic contamination signal computation.",
    class: "verification",
    node_kind: "checker",
    execution_type: "script",
    gate_policy: "required",
    license: CC,
    extraction_artifact_id: "CAP-M5-14",
    script_validator: { validator_id: "contamination-signals-script", entrypoint_path: "validators/contamination-signals.py", args_template: ["{outputs_json}"] },
    knowledge_sources: [{ knowledge_id: "degradation-registry", extraction_artifact_id: "KP-M4-03", output_path: "knowledge/degradation-registry.json" }],
    inputs: [{ role: "corpus", schema_ref: "corpus.v1", required: true, source_policy: "node_output" }],
    outputs: [{ role: "contamination_report", schema_ref: "contamination.v1", required: true }],
  }
];
